excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://andreycattalin.github.io
title: Andrey Cattalin
tagline: A log of everyday life
description: My awesome new site
paginate: 5
gems:
  - jekyll-sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
    safe: true
